transitiverobotics/transitive

- cloud/app/assets/install.sh
- cloud/app/web_components/robot-agent-device.jsx
- cloud/docker-compose.yaml
- was previously only working in docker install case
> agent install: pass TR_INSTALL_HASH along in systemd installation path

- cloud/registry/Dockerfile
- cloud/registry/index.js
- allows updating package meta-data without publishing new version of package
> registry: added custom route packageMeta

- cloud/app/server/server.js
- This is required to embed web components in other pages when these components need to make (authenticated) requests to the caps-web-server
> app/server: caps-router, accept Authorization header for auth

- robot-agent/aptLocal.sh
- robot-agent/package-lock.json
- robot-agent/package.json
> aptLocal: fix bug in ubuntu 22: no ROS one repo

- robot-agent/package-lock.json
- robot-agent/package.json
- robot-agent/revertuid.c
- robot-agent/unshare.sh
- robot-agent/unshared.sh
See #479#issuecomment-2052120944
> robot-agent, revertuid: handle long uids

- robot-agent/docker_install.js
- robot-agent/package-lock.json
- robot-agent/package.json
- robot-agent/preinstallPackage.sh
- robot-agent/startPackage.sh
Fixes part of #483.
Fixes #484.
> robot-agent: source ROS during preinstall; fix upgrade to node20

- cloud/mosquitto/auth-transitive/mosquitto_auth_transitive.cpp
This should (hopefully!) fix:
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string: construction from null is not valid
```
I believe the actual cause of the cases we saw was in the disconnect handler, when the user has no id (perhaps from attempts by some malicious actors?), because in most cases in the log the abort happened after a client disconnected.
> mqtt c++ auth: guards against null pointers

- cloud/mosquitto/auth-transitive/mosquitto_auth_transitive.cpp
- cloud/mosquitto/auth-transitive/tests.cpp
Fixes https://github.com/transitiverobotics/transitive-chfritz/issues/528.
> mosquitto auth: add catch-all and added missing test cases

- cloud/app/package-lock.json
- cloud/app/package.json
- cloud/app/server/server.js
- cloud/app/src/App.jsx
- cloud/app/src/utils/Embed.jsx
> cloud/app: fix removing device, add Documentation link to caps page

- cloud/app/esbuild.js
- cloud/app/package-lock.json
- cloud/app/package.json
- cloud/app/server/server.js
- robot-agent/mqtt.js
- robot-agent/package.json
See https://github.com/transitiverobotics/transitive-chfritz/issues/540#issuecomment-2475189296
> Migrate _fleet config

- robot-agent/localMQTT.js
- robot-agent/mqtt.js
- robot-agent/package-lock.json
- robot-agent/package.json
- Do not retain any messages in local broker.
- Updated aedes-preunsub to 0.51.3.
Fixes #512.
> robot-agent@2.2.2: no local retain, update Aedes

- cloud/app/src/utils/Embed.jsx
`TransitiveCapability` as of sdk v0.12.15 supports secondary UI components. This commit updates the Embed modal to show how.
> portal: updated Embed modal re. `TransitiveCapability` w/ 2nd UIs

- robot-agent/generate_certs.sh
- robot-agent/package-lock.json
- robot-agent/package.json
> Robot-agent: Revert allowing dashes in IDs

- cloud/app/server/server.js
Fixes https://github.com/transitiverobotics/transitive-chfritz/issues/366#issuecomment-2652152994
> cloud/app: serve @transitive-robotics caps from cloud registry

- cloud/app/package-lock.json
- cloud/app/package.json
- cloud/docker-compose.yaml
- robot-agent/package-lock.json
- robot-agent/package.json
- robot-agent/startPackage.sh
- using utils 0.12.17 which includes Jazzy in `rosReleases`
- also added Kilted already
> Add Jazzy to list of ROS releases

- cloud/app/server/server.js
- cloud/app/src/Admin.jsx
- cloud/mosquitto/auth-transitive/mosquitto_auth_transitive.cpp
> Issue#605 pay by invoice

- cloud/mosquitto/auth-transitive/isAuthorized.hpp
- cloud/mosquitto/auth-transitive/mosquitto_auth_transitive.cpp
- cloud/mosquitto/auth-transitive/tests.cpp
- robot-agent/config.js
This fixes a bug seen with file-sync, where the listing was not visible.
> mosquitto auth: fix bug in isAuthorized when limiting to topics

- robot-agent/package-lock.json
- robot-agent/package.json
- robot-agent/selfChecks.js
Doesn't work reliably and causes false positive warnings for users.
> robot-agent: disable bash default check

- cloud/mosquitto/Dockerfile
- cloud/mosquitto/auth-transitive/isAuthorized.hpp
- cloud/mosquitto/auth-transitive/mosquitto_auth_transitive.cpp
Prevents #615 from crashing (and hence restarting) mosquitto for now, but doesn't really solve the issue. Still haven't figured out the culprit.
> mosquitto-plugin: upgrade to mongoc++4.1 and try-catch exceptions

- cloud/app/server/server.js
- needed by video-recorder capability to fetch chapters when embedded elsewhere
> portal, server: allow authorization via jwt query param

- cloud/app/server/server.js
- robot-agent/index.js
- robot-agent/logMonitor.js
- robot-agent/package.json
- robot-agent/start_agent.sh
- robot-agent/utils.js
Cherry picked changes from 
https://github.com/transitiverobotics/transitive/pull/92
> Improved log uploading logic

- robot-agent/mqtt.js
Fixes issue reported in https://github.com/transitiverobotics/issues/issues/400#issuecomment-3025000081
ipconfig.io is down, we replaced it with a combination of ipify.org to get public ip + hackertarget to get geographic data
> replaced ipconfig with ipify+https://github.com/transitiverobotics/issues/issues/400#issuecomment-3025000081

- robot-agent/index.js
- robot-agent/localMQTT.js
- robot-agent/logMonitor.js
- robot-agent/mqtt.js
- robot-agent/resourceMonitor.js
- robot-agent/utils.js
- watching /status/package topic to start/stop resource and logs monitoring
- adds initial update for status watch which was not happening based on changes in some cases
> handling stopped packages for log and resource monitoring

- README.md
simple README update, docker compose command, just removed the "-" as all docker-compose became docker compose
> simple README update, docker compose command 

- cloud/app/public/style.css
- cloud/app/src/App.jsx
- cloud/app/src/Sidebar.jsx
- cloud/app/src/TransitiveLogo.jsx
https://github.com/user-attachments/assets/ca109800-3455-4cf3-9fd2-a5b467e63344
partially solves: https://github.com/transitiverobotics/issues/issues/332
> Sidebar auto hides
